Add VPC IPs to `linode_instance_networking` Data Source
linode/terraform-provider-linode pull request #1379
Opened 2024-04-03 20:50 UTC by zliang-akamai

## 📝 Description

**What does this PR do and why is this change necessary?**

## ✔️ How to Test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run the relevant unit/integration tests?**

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

2024-04-04 14:51 UTC, lgarber-akamai requested changes
This looks great! Could you also update the docs when you get a chance?

2024-04-04 18:29 UTC, zliang-akamai commented
Oh, I forgot the doc.. Thanks for the reminder! @lgarber-akamai

2024-04-08 15:19 UTC, lgarber-akamai commented on linode/instancenetworking/datasource_test.go
> +	t.Log(name)
Looks like a log statement was left behind 👀

2024-04-08 15:20 UTC, lgarber-akamai approved these changes
All tests are passing on my end, nice work!

2024-04-08 17:23 UTC, zliang-akamai commented on linode/instancenetworking/datasource_test.go
> +	t.Log(name)
Thanks!

2024-04-08 17:23 UTC, zliang-akamai commented
Oh not, I forgot description again... Sorry

2024-04-09 16:18 UTC, lgarber-akamai approved these changes
Re-approval for the provider config fix

2024-04-09 16:19 UTC, jriddle-linode approved these changes
LGTM. test passing locally.

2024-04-09 17:00 UTC, merged