Make firewall protocol case-insensitive
linode/terraform-provider-linode pull request #236
Opened 2021-03-15 15:04 UTC by LBGarber

This pull requests makes the `protocol` field for firewall rules accept any case.

2021-03-15 16:52 UTC, Charliekenney23 requested changes

2021-03-15 16:54 UTC, Charliekenney23 commented on linode/resource_linode_firewall.go
> +				ValidateFunc: validation.StringInSlice([]string{"TCP", "UDP", "ICMP"}, true),
This way if the API changes to include an additional protocol or something, we can support it without changes. And if the user provides an invalid one, the API will just respond with a 400 bad request, which we will propagate to the users.

2021-03-15 16:55 UTC, LBGarber commented on linode/resource_linode_firewall.go
> +				ValidateFunc: validation.StringInSlice([]string{"TCP", "UDP", "ICMP"}, true),
Good idea!

2021-03-15 18:28 UTC, Charliekenney23 approved these changes

2021-03-19 18:11 UTC, phillc approved these changes

2021-03-19 18:26 UTC, merged