Add ACL and CorsEnabled fields to Object Storage bucket resource
linode/terraform-provider-linode pull request #238
Opened 2021-03-17 15:49 UTC by LBGarber

- Add `acl` and `cors_enabled` field to Object Storage bucket resource
- Add `TestAccLinodeObjectStorageBucket_access`
- Update documentation to reflect changes

2021-03-17 16:49 UTC, Charliekenney23 requested changes

2021-03-17 16:49 UTC, Charliekenney23 commented on linode/resource_linode_object_storage_bucket.go
> +	err := client.UpdateObjectStorageBucketAccess(context.Background(), cluster, label, updateOpts)
since `err` isn't used outside of the `if` block, I'd do `if err := Func(); err != nil { ... }`.

2021-03-17 16:49 UTC, Charliekenney23 commented on linode/resource_linode_object_storage_bucket.go
> +		fmt.Errorf("Error updating Linode ObjectStorageBucket access: %s", err)
I would avoid using the word `error` in error messages. Also, error strings shouldn't be capitalized. https://github.com/golang/lint/blob/738671d3881b9731cc63024d5d88cf28db875626/lint.go#L1178

2021-03-17 16:49 UTC, Charliekenney23 commented on linode/resource_linode_object_storage_bucket.go
> +	if d.HasChange("acl") || d.HasChange("cors_enabled") {
swap for `d.HasChanges("acl", "cors_enabled")`

2021-03-17 17:06 UTC, Charliekenney23 requested changes

2021-03-17 17:06 UTC, Charliekenney23 commented on linode/resource_linode_object_storage_bucket.go
> +		fmt.Errorf("failed to update bucket access: %s", err)
make sure you return this error

2021-03-17 17:07 UTC, Charliekenney23 commented on linode/resource_linode_object_storage_bucket.go
> +		fmt.Errorf("Error finding the access config for the specified Linode ObjectStorageBucket: %s", err)
One more error message that needs revising

2021-03-17 18:00 UTC, Charliekenney23 approved these changes

2021-03-19 18:08 UTC, phillc commented on linode/resource_linode_object_storage_bucket.go
> +		return fmt.Errorf("failed to parse Linode ObjectStorageBucket id %s", d.Id())
make sure some reference to error message changes makes it into the changelog on release, in case someone is grepping for the old text.

2021-03-19 18:10 UTC, phillc commented on website/docs/r/object_storage_bucket.html.md
> +* `acl` - (Optional) The Access Control Level of the bucket using a canned ACL string. See all ACL strings [here](linode.com/docs/api/object-storage/#object-storage-bucket-access-update__request-body
s/here/in the Linode documentation/ or something like that.

2021-03-19 18:10 UTC, phillc approved these changes

2021-03-19 18:22 UTC, merged