don't use linodego SetPollDelay
linode/terraform-provider-linode pull request #239
Opened 2021-03-17 19:33 UTC by Charliekenney23

2021-03-17 19:49 UTC, phillc requested changes
https://github.com/linode/terraform-provider-linode/commit/5e5dcf8da0d4a05167ca9dfb8482dfd74fa0bf23 also added the constant to the Config. Is your intent to remove EventPollMilliseconds completely?

2021-03-17 19:59 UTC, Charliekenney23 commented
@phillc no LKE cluster recycles are dependent on EventPollMilliseconds

2021-03-17 21:30 UTC, LBGarber approved these changes

2021-03-18 14:09 UTC, phillc approved these changes

2021-03-18 14:57 UTC, merged