Add NodeBalancer-related data sources
linode/terraform-provider-linode pull request #244
Opened 2021-03-24 18:07 UTC by LBGarber

This pull request adds the following data sources:
- `linode_nodebalancer`
- `linode_nodebalancer_config`
- `linode_nodebalancer_node`

2021-03-25 03:11 UTC, Charliekenney23 requested changes

2021-03-25 03:11 UTC, Charliekenney23 commented on linode/data_source_linode_nodebalancer_config.go
> +				Elem: &schema.Resource{
This resource schema could also be reused

2021-03-25 03:11 UTC, Charliekenney23 commented on linode/data_source_linode_nodebalancer_config_test.go
> +data "linode_nodebalancer_config" "foofig" {
I love `foofig` lol

2021-03-25 03:11 UTC, Charliekenney23 commented on linode/data_source_linode_nodebalancer_test.go
> +					testAccCheckLinodeNodeBalancerExists,
make sure transfer is set here

2021-03-25 14:14 UTC, LBGarber commented on linode/data_source_linode_nodebalancer_config_test.go
> +data "linode_nodebalancer_config" "foofig" {
Same lol

2021-03-26 18:52 UTC, Charliekenney23 approved these changes

2021-03-26 19:58 UTC, merged