LKE - Add support for pool tags and custom disk partitions.
linode/terraform-provider-linode pull request #569
Opened 2021-12-13 04:22 UTC by kekoav

For LKE, adds pool tags and custom disk partitions. This support is already present in the golinode library and API, just exposing it for Terraform.

2021-12-13 14:48 UTC, LBGarber requested changes
Hey there! Thanks for the great contribution :smile: 

Just a few small changes and we should be good to go. Do you mind if I push a commit to this PR shortly to add integration tests?

2021-12-13 14:48 UTC, LBGarber commented on linode/lke/cluster.go
> +}
Just a small stylistic change :+1: 
```suggestion
return pool.Type == declaredPool["type"] && pool.Count == declaredPool["count"]
```

2021-12-13 14:57 UTC, LBGarber requested changes
Just a few changes to get the docs workflow passing

2021-12-13 14:57 UTC, LBGarber commented on website/docs/r/lke_cluster.html.md
> +
This should fix the docs linting workflow
```suggestion
```

2021-12-13 14:57 UTC, LBGarber commented on website/docs/d/lke_cluster.html.md
> +    * `type` - The filesystem type of the partition. (`raw`, `ext4`)
Remove trailing space for docs linting
```suggestion
    * `type` - The filesystem type of the partition. (`raw`, `ext4`)
```

2021-12-13 15:48 UTC, kekoav commented
@LBGarber I don't mind at all! It's all yours, your changes look good to me.

2021-12-13 15:54 UTC, kekoav commented
@LBGarber I was trying to add some integration tests, but it turned out it was going to be more than I bargained for... Adding Tags and Disk to `ClusterPoolSpec` no longer made it suitable for use as a map key which it was in several places, and I just didn't have the time to dig into how all that worked.

2021-12-13 17:49 UTC, LBGarber commented
While writing the integration tests I ran into a few issues with how update logic is handled. I'll see what I can do about this and get back to you! :+1:

2021-12-16 00:18 UTC, LBGarber commented
@kekoav Thanks for the feedback! I definitely agree with you there, a full cluster recreation should only be a last resort and shouldn't be triggered by a node pool update. I think it would vastly simplify the update logic here to have node pools be their own resource, but this currently doesn't mesh well with the existing LKE API architecture. I'll see what I can do about implementing disks into the existing node pool update logic.
 
> Let me know how I can help, I don't want to get in the way but would be happy to provide use cases from the perspective of a typical Kubernetes user.

Feedback is always appreciated! If you have any ideas or suggestions, feel free to let me know :slightly_smiling_face:

2022-04-03 00:54 UTC, LBGarber commented
Sorry about that, looks like the stale workflow didn't respect the `keep` tag.

2022-06-08 00:13 UTC, closed without merging

2023-05-28 11:20 UTC, akoidan commented
Is there anything preventing reopening and merging this PR? I'm facing the same issue, unable to get nodes of a newly created cluster described [here](https://github.com/linode/terraform-provider-linode/issues/595#issuecomment-1566092555)